[theme]
primaryColor = "#FF4B4B"  # 뉴로핏 레드 컬러
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"  # 더 밝은 배경색으로 변경
textColor = "#262730"
font = "sans serif"

[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false 